=== kotlin2018/mbt/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2017 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use it file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (resultMap*  | sql* | insert* | update* |updateTemplate* | delete* |deleteTemplate* | select* | selectTemplate* | insertTemplate* )+>
        <!ATTLIST mapper
                >

        <!ELEMENT resultMap (id*,result*)>
        <!ATTLIST resultMap
                id CDATA #REQUIRED
                table  #REQUIRED
                >

        <!ELEMENT id EMPTY>
        <!ATTLIST id
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                >

        <!ELEMENT result EMPTY>
        <!ATTLIST result
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                version_enable CDATA #IMPLIED
                logic_enable CDATA #IMPLIED
                logic_deleted CDATA #IMPLIED
                logic_undelete CDATA #IMPLIED
                >

        <!ELEMENT arg EMPTY>
        <!ATTLIST arg
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT typeAlias EMPTY>
        <!ATTLIST typeAlias
                alias CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT select (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST select
                id CDATA #REQUIRED
                resultMap CDATA #IMPLIED
                lang CDATA #IMPLIED
                >

        <!ELEMENT selectTemplate (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST selectTemplate
                id CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                lang CDATA #IMPLIED
                table CDATA #IMPLIED
                column CDATA #IMPLIED
                where CDATA #IMPLIED
                >


        <!ELEMENT insert (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST insert
                id CDATA #REQUIRED


                useGeneratedKeys (true|false) #IMPLIED
                lang CDATA #IMPLIED
                >

        <!ELEMENT insertTemplate (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST insertTemplate
                id CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                table CDATA #IMPLIED
                insert CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                >

        <!ELEMENT update (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST update
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                >
        <!--set指定值(例如 sets="name?name = #{name}"  )会更新对应值，否则为""设置全部属性-->
        <!ELEMENT updateTemplate (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST updateTemplate
                id CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                lang CDATA #IMPLIED
                table CDATA #IMPLIED
                set CDATA #IMPLIED
                where CDATA #IMPLIED
                >

        <!ELEMENT delete (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST delete
                id CDATA #REQUIRED

                lang CDATA #IMPLIED
                >
        <!ELEMENT deleteTemplate (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST deleteTemplate
                id CDATA #IMPLIED

                lang CDATA #IMPLIED
                table CDATA #IMPLIED
                where CDATA #IMPLIED
                resultMap (BaseResultMap) #IMPLIED
                >
        <!-- Dynamic -->

        <!ELEMENT include (property+)?>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >

        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT sql (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST sql
                id CDATA #REQUIRED
                lang CDATA #IMPLIED

                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                trimPrefix CDATA #IMPLIED
                suffix CDATA #IMPLIED
                trimSuffix CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ELEMENT set (#PCDATA | include | trim | where | set | for | switch | if | bind)*>

        <!ELEMENT for (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST for
                list CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT switch (case* , default?)>
        <!ELEMENT case (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST case
                test CDATA #REQUIRED
                >
        <!ELEMENT default (#PCDATA | include | trim | where | set | for | switch | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | for | switch | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== kotlin2018/mbt/example/xml/biz_activity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://gitee.com/gopher2011/mbt/blob/master/mybatis-3-mapper.dtd">
<mapper>
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
    <resultMap id="BaseResultMap" table="biz_activity">
    	<result column="id" langType="string"  />
	<result column="name" langType="string"  />
	<result column="pc_link" langType="string"  />
	<result column="h5_link" langType="string"  />
	<result column="remark" langType="string"  />
	<result column="sort" langType="int"  />
	<result column="status" langType="int"  />
	<result column="version" langType="int"  />
	<result column="create_time" langType="time.Time"  />
	<result column="delete_flag" langType="int"  />
    </resultMap>
	<!--模板标签: column where set 以逗号 ',' 分隔表达式，? 为判空表达式-->
	<!--插入模板:默认id="insertTemplate,test="field != null",where自动设置逻辑删除字段,支持批量插入" -->
	<insertTemplate/>

	<!--查询模板:默认id="selectTemplate,where自动设置逻辑删除字段-->
	<selectTemplate where="name=#{name} or pc_link=#{pc_link}"/>

	<!--更新模板:默认id="updateTemplate,set自动设置乐观锁版本号-->
	<updateTemplate set="name?name = #{name},remark?remark=#{remark}" where="id?id = #{id}"/>

	<!--删除模板:默认id="deleteTemplate,where自动设置逻辑删除字段-->
	<deleteTemplate where="name?name = #{name}"/>

	<!--批量插入例子: 因为上面已经有id="insertTemplate" 需要指定id -->
	<insertTemplate id="InsertTemplateBatch"/>

	<!--统计模板例子:-->
	<selectTemplate id="selectCountTemplate" column="count(*)" where="name?name = #{name}"/>

	<!--自定义的函数对应的 SQL语句	-->
	<sql id="column">
		id,name,pc_link,h5_link,remark,sort,status,version,create_time,delete_flag
	</sql>

	<select id="selectTpl">select * from biz_activity where name = #{name}</select>

	<select id="selectByName">
		select
		<include refid="column"/>
		from biz_activity where `name` = #{name} and pc_link = #{pc_link}
	</select>

	<select id="selectByCondition" resultMap="BaseResultMap">
		<bind name="pattern" value="'%' + name + '%'"/>
		select * from biz_activity
		<where>
			<if test="name != null">and name like #{pattern}</if>
			<if test="start_time != null">and create_time >= #{start_time}</if>
			<if test="end_time != null">and create_time &lt;= #{end_time}</if>
		</where>
		order by create_time desc
		<if test="page != null and size != null">limit #{page}, #{size}</if>
	</select>

	<!-- if 标签中对于参数的判空，统一使用 nil -->
	<select id="selectByCondition2" resultMap="BaseResultMap">
		<bind name="pattern" value="'%' + name + '%'"/>
		select * from biz_activity
		<where>
			<if test="name != nil">and name like #{pattern}</if>
			<if test="start_time != nil">and create_time >= #{start_time}</if>
			<if test="end_time != nil">or create_time &lt;= #{end_time}</if>
		</where>
		order by create_time desc
		<if test="page != nil and size != nil">limit #{page}, #{size}</if>
	</select>

	<select id="countByCondition">
		select count(id) from biz_activity where delete_flag = 1
		<if test="name != null">and name like concat('%',#{name},'%')</if>
		<if test="start_time !=nil">and create_time >= #{start_time}</if>
		<if test="end_time != nil">and create_time &lt;= #{end_time}</if>
	</select>

	<select id="selectAll">
		select * from biz_activity where delete_flag = 1 order by create_time desc
	</select>

	<select id="selectByUUID">
		select * from biz_activity where uuid = #{uuid} and delete_flag = 1
	</select>

	<select id="selectById">
		select * from biz_activity where id = #{id} and delete_flag = 1
	</select>

	<select id="selectByIds">
		select * from biz_activity where delete_flag = 1
		<for list="ids" index="index" item="item"  open=" and id in(" close=")" separator=",">
			#{item}
		</for>
	</select>

	<!-- 这个SQL语句与上面的一样，只是写法不同 -->
	<select id="selectByIds2">
		select * from biz_activity where delete_flag = 1 and id in
		<for list="ids" index="index" item="item"  open="(" close=")" separator=",">
			#{item}
		</for>
	</select>

	<select id="selectByIdMaps">
		select * from biz_activity where delete_flag = 1
		<for list="ids" open=" and id in(" close=")" index="index" item="item" separator=",">
			#{item}
		</for>
		<for list="ids" open=" and delete_flag in(" close=")" index="index" item="item" separator=",">
			#{index}
		</for>
	</select>

	<!-- 软删除 -->
	<update id="removeById">
		update biz_activity set delete_flag = 0 where id = #{id}
	</update>

	<!-- 物理删除 -->
	<delete id="deleteById">
		delete from biz_activity where id = #{id}
	</delete>

	<delete id="DeleteByIds">
		delete from biz_activity where id in
		<for list="ids" close=")" open="(" index="index" item="item" separator=",">
			#{item}
		</for>
	</delete>

	<update id="updateById">
		update biz_activity
		<set>
			<if test="name !=nil">name = #{name},</if>
			<if test="pc_link !=nil">pc_link = #{pc_link},</if>
			<if test="h5_link !=nil">h5_link = #{h5_link},</if>
			<if test="remark !=nil">remark = #{remark},</if>
			<if test="create_time !=nil">create_time = #{create_time},</if>
			<if test="delete_flag !=nil">delete_flag = #{delete_flag},</if>
		</set>
		where id = #{id} and delete_flag = 1
	</update>

	<insert id="insert">
		insert into biz_activity
		<trim prefix="(" suffix=")" trimSuffix=",">
			<if test="id != nil">id,</if>
			<if test="name != nil">name,</if>
			<if test="pc_link != nil">pc_link,</if>
			<if test="h5_link != nil">h5_link,</if>
			<if test="remark != nil">remark,</if>
			<if test="create_time != nil">create_time,</if>
			<if test="delete_flag != nil">delete_flag,</if>
		</trim>

		<trim prefix="values (" suffix=")" trimSuffix=",">
			<if test="id != nil">#{id},</if>
			<if test="name != nil">#{name},</if>
			<if test="pc_link != nil">#{pc_link},</if>
			<if test="h5_link != nil">#{h5_link},</if>
			<if test="remark != nil">#{remark},</if>
			<if test="create_time != nil">#{create_time},</if>
			<if test="delete_flag != nil">#{delete_flag},</if>
		</trim>
	</insert>

	<select id="choose">
		select * from biz_activity
		<switch>
			<case test="delete_flag >1">where delete_flag > 1</case>
			<case test="delete_flag ==1">where delete_flag = 1</case>
			<default>where delete_flag &lt; 1</default>
		</switch>
	</select>

	<sql id="link">
		pc_link,h5_link
		<!--不启用TypeConvert的话，使用${} 而不是 #{}-->
		<if test="column != nil">,${column}</if>
	</sql>

	<select id="selectLinks">
		select
		<include refid="link"/>
		from biz_activity where delete_flag = 1
	</select>

	<sql id="choose02">
		select * from biz_activity
	</sql>
	<select id="Choose2">
		select * from biz_activity where
		<if test="name!=nil">name = #{name}</if>
		<if test="pc_link!=nil">or pc_link = #{pc_link}</if>
	</select>
</mapper>

=== kotlin2018/mbt/example/xml/ums_admin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://gitee.com/gopher2011/mbt/blob/master/mybatis-3-mapper.dtd">
<mapper>
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
    <resultMap id="BaseResultMap" table="ums_admin">
    	<result column="id" langType="int64"  />
	<result column="parent_id" langType="int64"  />
	<result column="username" langType="string"  />
	<result column="password" langType="string"  />
	<result column="icon" langType="string"  />
	<result column="email" langType="string"  />
	<result column="nick_name" langType="string"  />
	<result column="note" langType="string"  />
	<result column="create_time" langType="time.Time"  />
	<result column="login_time" langType="time.Time"  />
	<result column="status" langType="int32"  />
    </resultMap>
	<insertTemplate/>

	<select id="getBase">
		select id,username,password,icon from ums_admin
	</select>

	<select id="usernameEqualTo" >
		select * from ums_admin where username = #{username} order by id desc;
	</select>

	<insert id="insert">
		insert into ums_admin
		<trim prefix="(" suffix=")" trimSuffix=",">
			<if test="id != nil">id,</if>
			<if test="username != nil">username,</if>
			<if test="password != nil">password,</if>
			<if test="icon != nil">icon,</if>
			<if test="email != nil">email,</if>
			<if test="nick_name != nil">nick_name,</if>
			<if test="note != nil">note,</if>
			<if test="create_time != nil">create_time,</if>
			<if test="login_time != nil">login_time,</if>
			<if test="status != nil">status,</if>
		</trim>
		<trim prefix="values (" suffix=")" trimSuffix=",">
			<if test="id != nil">#{id},</if>
			<if test="username != nil">#{username},</if>
			<if test="password != nil">#{password},</if>
			<if test="icon != nil">#{icon},</if>
			<if test="email != nil">#{email},</if>
			<if test="nick_name != nil">#{nick_name},</if>
			<if test="note != nil">#{note},</if>
			<if test="create_time != nil">#{create_time},</if>
			<if test="login_time != nil">#{login_time},</if>
			<if test="status != nil">#{status},</if>
		</trim>
	</insert>

	<sql id="column">
		id,username,password,icon,email,nick_name,note,create_time,login_time,status
	</sql>

	<select id="selectByPrimaryKey">
		select
		<include refid="column"/>
		from ums_admin
		where id = #{id}
	</select>

	<select id="userExist">
		select
		<include refid="column"/>
		from ums_admin
		<where>
			<if test="username!=''">username = #{username}</if>
			<if test="password!=''">and password = #{password}</if>
		</where>
	</select>

	<update id="updateColumn">update ums_admin set login_time = #{loginTime}</update>

	<select id="list">
		select
		<include refid="column"/>
		from ums_admin
		<where>
			<if test="keyword!=''">username like #{'%'+keyword+'%'} or nick_name like #{'%'+keyword+'%'}</if>
		</where>
		limit #{pageNum},#{pageSize}
	</select>

	<updateTemplate id="updateByPrimaryKeySelective" where="id = #{id}"/>

	<select id="getAdmin">
		select * from ums_admin
		<where>
			<if test="username!=''">username = #{username}</if>
			<if test="password!=''">and password = #{password}</if>
		</where>
		order by id desc;
	</select>

	<update id="updatePassword">
		update ums_admin
		set password = #{password}
		where id = #{id}
	</update>

	<update id="updateByPrimaryKey">
		update ums_admin
		set username = #{username},
			password = #{password},
			icon = #{icon},
			email = #{email},
			nick_name = #{nickName},
			note = #{note},
			status = #{status}
		where id = #{id}
	</update>

	<delete id="deleteByPrimaryKey">delete from ums_admin where id=#{id}</delete>

	<select id="listWithChildren">
		select a1.* ,
			   a2.*
		from ums_admin as a1
				 left join ums_admin as a2 on a1.id = a2.parent_id
		where a1.parent_id=0
	</select>
</mapper>
