=== kotlin2018/mbt/mybatis.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2017 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use it file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (resultMap*  | sql* | insert* | update* | delete* | select* | execute*)+>
        <!ATTLIST mapper
                namespace CDATA #IMPLIED
                >

        <!ELEMENT resultMap (id*,result*)>
        <!ATTLIST resultMap
                id CDATA #REQUIRED
                table  #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT id EMPTY>
        <!ATTLIST id
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                property CDATA #IMPLIED
                >

        <!ELEMENT result EMPTY>
        <!ATTLIST result
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                property CDATA #IMPLIED
                version_enable CDATA #IMPLIED
                logic_enable CDATA #IMPLIED
                logic_deleted CDATA #IMPLIED
                logic_undelete CDATA #IMPLIED
                >

        <!ELEMENT arg EMPTY>
        <!ATTLIST arg
                langType CDATA #IMPLIED
                column CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT typeAlias EMPTY>
        <!ATTLIST typeAlias
                alias CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST select
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                table CDATA #IMPLIED
                column CDATA #IMPLIED
                where CDATA #IMPLIED
                >

        <!ELEMENT execute (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST execute
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                useGeneratedKeys (true|false) #IMPLIED
                table CDATA #IMPLIED
                insert CDATA #IMPLIED
                set CDATA #IMPLIED
                where CDATA #IMPLIED
                >

        <!ELEMENT insert (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST insert
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                useGeneratedKeys (true|false) #IMPLIED
                table CDATA #IMPLIED
                insert CDATA #IMPLIED
                >

        <!--set指定值(例如 sets="name?name = #{name}"  )会更新对应值，否则为""设置全部属性-->
        <!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST update
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                table CDATA #IMPLIED
                set CDATA #IMPLIED
                where CDATA #IMPLIED
                >

        <!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST delete
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                table CDATA #IMPLIED
                where CDATA #IMPLIED
                >

        <!-- Dynamic -->
        <!ELEMENT include (property+)?>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >

        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST sql
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>
        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== kotlin2018/mbt/example/xml/RoleDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "https://github.com/kotlin2018/mbt/blob/master/mybatis.dtd">
<mapper namespace="com.macro.mall.mapper.RoleDao">
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
	<resultMap id="base" table="ums_role">
    	<result column="id" property="Id" langType="int64"  />
		<result column="pid" property="Pid" langType="int"  />
	<result column="name" property="Name" langType="string"  />
	<result column="description" property="Description" langType="string"  />
	<result column="admin_count" property="AdminCount" langType="int32"  />
	<result column="create_time" property="CreateTime" langType="time.Time"  />
	<result column="status" property="Status" langType="int32"  />
	<result column="sort" property="Sort" langType="int32"  />
    </resultMap>
	<insert id="Insert" resultMap="base"/>
	<update id="Update"/>
	<delete id="Delete" resultMap="base"/>
	<select id="getItem" column="*" resultMap="base" where="id?id =#{id}"/>

	<delete id="deleteAll">delete from ums_role</delete>

<!--	<select id="getItem"/>-->

</mapper>

=== kotlin2018/mbt/example/xml/ActivityDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "https://github.com/kotlin2018/mbt/blob/master/mybatis.dtd">
<mapper namespace="com.macro.mall.mapper.ActivityDao">
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
<!--	<resultMap id="base" table="activity">-->
<!--    	<result column="id" property="Id" langType="string"  />-->
<!--		<result column="uuid" property="uuid" langType="string"  />-->
<!--	<result column="name" property="Name" langType="string"  />-->
<!--	<result column="pc_link" property="PcLink" langType="string"  />-->
<!--	<result column="h5_link" property="H5Link" langType="string"  />-->
<!--	<result column="remark" property="Remark" langType="string"  />-->
<!--	<result column="sort" property="Sort" langType="int"  />-->
<!--	<result column="status" property="Status" langType="int"  />-->
<!--	<result column="version" property="Version" langType="int"  />-->
<!--	<result column="create_time" property="CreateTime" langType="time.Time"  />-->
<!--	<result column="delete_flag" property="DeleteFlag" langType="int"  />-->
<!--	<result column="salary" property="salary" langType="float64"  />-->
<!--    </resultMap>-->

<!--	<resultMap id="base" table="biz_activity">-->
<!--		<result column="id" property="Id" langType="string"  />-->
<!--		<result column="name" property="Name" langType="string"  />-->
<!--		<result column="pc_link" property="PcLink" langType="string"  />-->
<!--		<result column="sort" property="Sort" langType="int"  />-->
<!--		<result column="status" property="Status" langType="int"  />-->
<!--		<result column="version" property="Version" langType="int"  />-->
<!--		<result column="create_time" property="CreateTime" langType="time.Time"  />-->
<!--		<result column="delete_flag" property="DeleteFlag" langType="int"  />-->
<!--		<result column="salary" property="salary" langType="float64"  />-->
<!--	</resultMap>-->


		<resultMap id="base" table="biz_activity">
			<result column="id" property="" langType="string"  />
			<result column="name" property="" langType="string"  />
			<result column="pc_link" property="" langType="string"  />
			<result column="sort" property="" langType="int"  />
			<result column="status" property="" langType="int"  />
			<result column="version" property="" langType="int"  />
			<result column="create_time" property="" langType="time.Time"  />
			<result column="delete_flag" property="" langType="int"  />
			<result column="salary" property="" langType="float64"  />
		</resultMap>

	<!--标签的 resultMap 属性不为空，并且其对应的值也不为空，则它为模版标签 (注意: <select> 标签只有 column 、resultMap 这两个属性都不为空时，它才是模版标签)-->

	<!--插入模板:默认id="insert" 支持批量插入 -->
	<insert id="insertTemplate" resultMap="base"/>

	<!--删除模板:默认id="delete",where自动设置逻辑删除字段-->
	<delete id="deleteTemplate" resultMap="base" where="name?name = #{name}"/>

	<!--更新模板:默认id="update",set自动设置乐观锁版本号-->
	<update id="updateTemplate" resultMap="base" set="name?name = #{name},pc_link?pc_link=#{pc_link}" where="id?id = #{id}"/>

	<!--查询模板:默认id="select",where自动设置逻辑删除字段-->
	<select id="selectTemplate" column="*" table="biz_activity" resultMap="base" where="name?name=#{name},pc_link?pc_link=#{pc_link}"/>

	<!--统计模板例子:-->
	<select id="selectCountTemplate" column="count(*)" resultMap="base" where="name?name = #{name}"/>

	<insert id="insertCollection" resultMap="base"/>

	<insert id="insertTemplateBatch" resultMap="base"/>

	<!--自定义的函数对应的 SQL语句	-->
	<sql id="column">
		id,name,pc_link,sort,status,version,create_time,delete_flag,salary
	</sql>

	<select id="selectByName">
		select
		<include refid="column"/>
		from biz_activity where name = #{name} and pc_link = #{pc_link}
	</select>

	<select id="selectTpl">select * from biz_activity where name = #{name}</select>

	<select id="selectTpl2">select * from biz_activity where name = #{name}</select>

	<select id="selectTpl3">select * from biz_activity where name = #{name}</select>

	<select id="SelectOneColumn">select  create_time from biz_activity where id = #{id}</select>

	<select id="selectByCondition" resultMap="BaseResultMap">
		<bind name="pattern" value="'%' + name + '%'"/>
		select * from biz_activity
		<where>
			<if test="name != null">and name like #{pattern}</if>
			<if test="start_time != null">and create_time >= #{start_time}</if>
			<if test="end_time != null">and create_time &lt;= #{end_time}</if>
		</where>
		order by create_time desc
		<if test="page != null and size != null">limit #{page} OFFSET #{size}</if>
	</select>

	<!-- if 标签中对于参数的判空，统一使用 nil -->
	<select id="selectByCondition2" resultMap="BaseResultMap">
		<bind name="pattern" value="'%' + Name + '%'"/>
		select * from biz_activity
		<where>
			<if test="Name != nil">and name like #{pattern}</if>
			<if test="StartTime != nil">and create_time >= #{StartTime}</if>
			<if test="EndTime != nil">and create_time &lt;= #{EndTime}</if>
		</where>
		order by create_time desc
		<if test="Page != nil and Size != nil">limit #{Page} OFFSET #{Size}</if>
	</select>

	<select id="countByCondition">
		select count(id) from biz_activity where delete_flag = 1
		<if test="name != null">and name like concat('%',#{name},'%')</if>
		<if test="start_time !=nil">and create_time >= #{start_time}</if>
		<if test="end_time != nil">and create_time &lt;= #{end_time}</if>
	</select>

	<select id="selectAll">
		select * from biz_activity where delete_flag = 1 order by create_time desc
	</select>

	<select id="selectByUUID">
		select * from biz_activity where uuid = #{uuid} and delete_flag = 1
	</select>

	<select id="selectById">
		select * from biz_activity where id = #{id} and delete_flag = 1
	</select>

	<select id="selectByIds">
		select * from biz_activity where delete_flag = 1
		<foreach collection="ids" index="index" item="item"  open=" and id in(" close=")" separator=",">
			#{item}
		</foreach>
	</select>

	<!-- 这个SQL语句与上面的一样，只是写法不同 -->
	<select id="selectByIds2">
		select * from biz_activity where delete_flag = 1 and id in
		<foreach collection="ids" index="index" item="item"  open="(" close=")" separator=",">
			#{item}
		</foreach>
	</select>

	<select id="selectByIdMaps">
		select * from biz_activity where delete_flag = 1
		<foreach collection="ids" open=" and id in(" close=")" index="index" item="item" separator=",">
			#{item}
		</foreach>
		<foreach collection="ids" open=" and delete_flag in(" close=")" index="index" item="item" separator=",">
			#{index}
		</foreach>
	</select>

	<!-- 软删除 resultMap == "" 则SQL语句不走模版-->
	<update id="removeById" resultMap="" where="id=#{id}">
		update biz_activity set delete_flag = 0 where id=#{id}
	</update>

	<!-- 物理删除 -->
	<delete id="deleteById">
		delete from biz_activity where id = #{id}
	</delete>

	<delete id="DeleteByIds">
		delete from biz_activity where id in
		<foreach collection="ids" close=")" open="(" index="index" item="item" separator=",">
			#{item}
		</foreach>
	</delete>

	<update id="updateById">
		update biz_activity
		<set>
			<if test="name !=nil">name = #{name},</if>
			<if test="pc_link !=nil">pc_link = #{pc_link},</if>
			<if test="create_time !=nil">create_time = #{create_time},</if>
			<if test="delete_flag !=nil">delete_flag = #{delete_flag},</if>
		</set>
		where id = #{id} and delete_flag = 1
	</update>

	<insert id="insert">
		insert into biz_activity
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<if test="id != nil">id,</if>
			<if test="name != nil">name,</if>
			<if test="pc_link != nil">pc_link,</if>
			<if test="create_time != nil">create_time,</if>
			<if test="delete_flag != nil">delete_flag,</if>
		</trim>
		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<if test="id != nil">#{id},</if>
			<if test="name != nil">#{name},</if>
			<if test="pc_link != nil">#{pc_link},</if>
			<if test="create_time != nil">#{create_time},</if>
			<if test="delete_flag != nil">#{delete_flag},</if>
		</trim>
	</insert>

	<insert id="insert2">
		insert into biz_activity
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<if test="id != nil">id,</if>
			<if test="name != nil">name,</if>
			<if test="pc_link != nil">pc_link,</if>
			<if test="create_time != nil">create_time,</if>
			<if test="delete_flag != nil">delete_flag,</if>
		</trim>
		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<if test="id != nil">#{id},</if>
			<if test="name != nil">#{name},</if>
			<if test="pc_link != nil">#{pc_link},</if>
			<if test="create_time != nil">#{create_time},</if>
			<if test="delete_flag != nil">#{delete_flag},</if>
		</trim>
	</insert>

	<select id="choose">
		select * from biz_activity
		<choose>
			<when test="delete_flag >1">where delete_flag > 1</when>
			<when test="delete_flag ==1">where delete_flag = 1</when>
			<otherwise>where delete_flag &lt; 1</otherwise>
		</choose>
	</select>

	<sql id="link">
		pc_link
		<!--不启用TypeConvert的话，使用${} 而不是 #{}-->
		<if test="column != nil">,${column}</if>
	</sql>

	<select id="selectLinks">
		select
		<include refid="link" />
		from biz_activity where delete_flag = 1
	</select>

	<sql id="choose02">
		select * from biz_activity
	</sql>

	<select id="Choose2">
		select * from biz_activity
		<where>
			<if test="name!=null">name = #{name}</if>
			<if test="pc_link!=null">or pc_link = #{pc_link}</if>
			and delete_flag = 1
		</where>
	</select>

	<select id="getSalary">select sum(salary) sum_val from biz_activity where create_time >= #{start_time} and create_time &lt;= #{end_time}</select>

	<select id="getId">
		select orders.id from orders where project_id = #{project_id} AND repository_id = #{repository_id}
	</select>

	<select id="getIdsByName">
		select biz_activity.name from biz_activity where biz_activity.name = #{name}
	</select>

	<select id="getName">
		select users.name from users where users.id = 3
	</select>

	<select id="getCreatedAt">
		select users.created_at from users where users.id = 3
	</select>
</mapper>

=== kotlin2018/mbt/example/xml/AdminDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "https://github.com/kotlin2018/mbt/blob/master/mybatis.dtd">
<mapper namespace="com.macro.mall.mapper.AdminDao">
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
	<resultMap id="example.UmsAdmin" table="ums_admin">
    	<result column="id" property="Id" langType="int64"  />
	<result column="parent_id" property="ParentId" langType="int64"  />
	<result column="username" property="Username" langType="string"  />
	<result column="password" property="Password" langType="string"  />
	<result column="icon" property="Icon" langType="string"  />
	<result column="email" property="Email" langType="string"  />
	<result column="nick_name" property="NickName" langType="string"  />
	<result column="note" property="Note" langType="string"  />
	<result column="create_time" property="CreateTime" langType="time.Time"  />
	<result column="login_time" property="LoginTime" langType="time.Time"  />
	<result column="status" property="Status" langType="int32"  />
    </resultMap>

	<!--插入模板:默认id="insert" 支持批量插入 -->
	<insert id="insertTemplate" resultMap="example.UmsAdmin"/>

	<!--删除模板:默认id="delete",where自动设置逻辑删除字段-->
	<delete id="delete" resultMap="example.UmsAdmin"/>

	<!--更新模板:默认id="update",set自动设置乐观锁版本号-->
	<update id="update" resultMap="example.UmsAdmin"/>

	<!--查询模板:默认id="select",where自动设置逻辑删除字段-->
	<select id="select" resultMap="example.UmsAdmin"/>

	<select id="getBase">
		select id,username,password,icon from ums_admin
	</select>

	<select id="usernameEqualTo" >
		select * from ums_admin where username = #{username} order by id desc;
	</select>

	<insert id="insert">
		insert into ums_admin
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<if test="id != nil">id,</if>
			<if test="username != nil">username,</if>
			<if test="password != nil">password,</if>
			<if test="icon != nil">icon,</if>
			<if test="email != nil">email,</if>
			<if test="nick_name != nil">nick_name,</if>
			<if test="note != nil">note,</if>
			<if test="create_time != nil">create_time,</if>
			<if test="login_time != nil">login_time,</if>
			<if test="status != nil">status,</if>
		</trim>
		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<if test="id != nil">#{id},</if>
			<if test="username != nil">#{username},</if>
			<if test="password != nil">#{password},</if>
			<if test="icon != nil">#{icon},</if>
			<if test="email != nil">#{email},</if>
			<if test="nick_name != nil">#{nick_name},</if>
			<if test="note != nil">#{note},</if>
			<if test="create_time != nil">#{create_time},</if>
			<if test="login_time != nil">#{login_time},</if>
			<if test="status != nil">#{status},</if>
		</trim>
	</insert>

	<sql id="column">
		id,username,password,icon,email,nick_name,note,create_time,login_time,status
	</sql>

	<select id="selectByPrimaryKey">
		select
		<include refid="column"/>
		from ums_admin
		where id = #{id}
	</select>

	<select id="userExist">
		select
		<include refid="column"/>
		from ums_admin
		<where>
			<if test="username!=''">username = #{username}</if>
			<if test="password!=''">and password = #{password}</if>
		</where>
	</select>

	<update id="updateColumn">update ums_admin set login_time = #{loginTime}</update>

	<select id="list">
		select
		<include refid="column"/>
		from ums_admin
		<where>
			<if test="keyword!=''">username like #{'%'+keyword+'%'} or nick_name like #{'%'+keyword+'%'}</if>
		</where>
		limit #{pageNum},#{pageSize}
	</select>

	<update id="updateByPrimaryKeySelective" resultMap="example.UmsAdmin" where="id = #{id}"/>

	<select id="getAdmin">
		select * from ums_admin
		<where>
			<if test="username!=''">username = #{username}</if>
			<if test="password!=''">and password = #{password}</if>
		</where>
		order by id desc;
	</select>

	<update id="updatePassword">
		update ums_admin
		set password = #{password}
		where id = #{id}
	</update>

	<update id="updateByPrimaryKey">
		update ums_admin
		set username = #{username},
			password = #{password},
			icon = #{icon},
			email = #{email},
			nick_name = #{nickName},
			note = #{note},
			status = #{status}
		where id = #{id}
	</update>

	<delete id="deleteByPrimaryKey">delete from ums_admin where id=#{id}</delete>

	<select id="listWithChildren">
		select a1.* ,
			   a2.*
		from ums_admin as a1
				 left join ums_admin as a2 on a1.id = a2.parent_id
		where a1.parent_id=0
	</select>

	<delete id="deleteByIds">
		delete from ums_admin where id in
		<foreach collection="ids" open="(" close=")" index="index" item="item" separator=",">
			#{item}
		</foreach>
	</delete>

	<select id="selectUnion">
		select u.*,
		       r.id r_id, r.pid, r.name, r.description, r.admin_count, r.create_time r_create_time, r.status r_status, r.sort
		from ums_admin as u
				 inner join ums_role as r on r.pid = u.id
	</select>

	<update id="createUmsRole">
		create table ums_role(
			id          serial not null primary key,
			pid         int,
			name        varchar(100),
			description varchar(500),
			admin_count int,
			create_time timestamptz default CURRENT_TIMESTAMP,
			status      int,
			sort        int
		);
	</update>

	<update id="createUmsAdmin">
		create table ums_admin(
			id          serial not null primary key,
			parent_id   int,
			username    varchar(64),
			password    varchar(64),
			icon        varchar(500),
			email       varchar(100),
			nick_name   varchar(200),
			note        varchar(500),
			create_time timestamp default CURRENT_TIMESTAMP,
			login_time  timestamp default CURRENT_TIMESTAMP,
			status      int
		);
	</update>

	<update id="createBizActivity">
		CREATE TABLE biz_activity(
			id          serial         not null primary key,
			name        varchar(255)   NOT NULL             default '',
			pc_link     varchar(255)                        DEFAULT NULL,
			sort        int            NOT NULL             default 0,
			status      int            NOT NULL             default 0,
			version     int            NOT NULL             default 0,
			create_time timestamp                           default CURRENT_TIMESTAMP,
			delete_flag int            NOT NULL             default 0,
			salary      decimal(10, 2) NOT NULL             DEFAULT 0.00
		);
	</update>

	<select id="GetDB">
		select tablename from pg_tables where schemaname='public'
	</select>

</mapper>

=== kotlin2018/mbt/example/xml/ums_role.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://github.com/kotlin2018/mbt/blob/master/mybatis.dtd">
<mapper>
    <!--logic_enable 逻辑删除字段-->
    <!--logic_deleted 逻辑删除已删除字段-->
    <!--logic_undelete 逻辑删除 未删除字段-->
    <!--version_enable 乐观锁版本字段,支持int,int8,int16,int32,int64-->
    <resultMap id="BaseResultMap" table="ums_role">
    	<result column="id" langType="int64"  />
	<result column="name" langType="string"  />
	<result column="description" langType="string"  />
	<result column="admin_count" langType="int32"  />
	<result column="create_time" langType="time.Time"  />
	<result column="status" langType="int32"  />
	<result column="sort" langType="int32"  />
    </resultMap>
	<insert id="insert">
		insert into ums_role (name, description, admin_count, create_time, status, sort)
		values(#{name},#{description},#{admin_count},#{create_time},#{status},#{sort})
	</insert>

	<select id="getItem">select * from ums_role where id=#{id}</select>
</mapper>
